cp test.txt test1.txt
cat test.txt >> test1.txt
cat test1.txt >> test.txt
cat test.txt >> test1.txt
cat test1.txt >> test.txt
cat test.txt >> test1.txt
cat test1.txt >> test.txt
cat test.txt >> test1.txt
cat test1.txt >> test.txt
cat test.txt >> test1.txt
cat test1.txt >> test.txt
cat test.txt >> test1.txt
cat test1.txt >> test.txt
cat test.txt >> test1.txt
cat test1.txt >> test.txt
cat test.txt >> test1.txt
cat test1.txt >> test.txt
cat test.txt >> test1.txt
cat test1.txt >> test.txt
cat test.txt >> test1.txt
cat test1.txt >> test.txt
cat test.txt >> test1.txt
cat test1.txt >> test.txt
cat test.txt >> test1.txt
cat test1.txt >> test.txt
cat test.txt >> test1.txt
cat test1.txt >> test.txt
cat test.txt >> test1.txt
cat test1.txt >> test.txt
cat test.txt >> test1.txt
cat test1.txt >> test.txt
cat test.txt >> test1.txt
cat test1.txt >> test.txt
cat test.txt >> test1.txt
cat test1.txt >> test.txt
cat test.txt >> test1.txt
cat test1.txt >> test.txt
cat test.txt >> test1.txt
cat test1.txt >> test.txt
rm test1.txt
